### ISSUE TITLE
Code base complete?

### ISSUE THREAD

**Issue by cbsudux** [heefe92/Relation_Networks-pytorch#1]
Is the code base complete? I can't find code for the relation module in the repo.

**Comment by heefe92** [comment]
Hello.
I started this project now.
I will implement the relation module as soon as possible.
Thank you.

**Comment by cbsudux** [comment]
Alright! Let me know if you need any help.

**Comment by heefe92** [comment]
@cbsudux Thank you :D

**Comment by twmht** [comment]
@heefe92 

Did you complete the script to train nms in end to end?

**Comment by heefe92** [comment]
@twmht 

right.
I made them learn about VOC data.
But the performance is still not good.
I think fine tuning is necessary.

**Comment by twmht** [comment]
@heefe92 

so the code is able to train on voc datasets? How to run the training step?

**Comment by heefe92** [comment]
@twmht 
yes,
Modify the config.py file and run train.py.

**Comment by twmht** [comment]
@heefe92 

ok. looking forward for the fine-tuning.

**Comment by twmht** [comment]
@heefe92 

Can you share your current MAP with and without learning nms?

**Comment by heefe92** [comment]
@twmht 
About 0.5 for map @ 50.

**Comment by twmht** [comment]
@heefe92 

Well, Did you reference the original implementation in MXNET (https://github.com/heefe92/Relation_Networks-pytorch) ?

**Comment by heefe92** [comment]
@twmht 
right. I referenced MXNET to learn nms(https://github.com/msracver/Relation-Networks-for-Object-Detection/blob/master/relation_rcnn/operator_py/learn_nms.py).
